from . import add_identifiants_client_partner
from . import article_prix_de_vente
from . import unique_fields
from . import account_followup
from . import res_partner
from . import sale
from . import achat_origine
#from . import article_prix_achat
from . import stock_move
from . import purchase_order_line
from . import stock_quant
from . import product_product
from . import add_ref_code_article
from . import invoice_origin
from . import product_template
from . import show_product_description
