[options]
admin_passwd = $ODOO_ADMIN_PASSWD
db_host = postgres
db_port = 5432
db_user = odoo
db_password = $POSTGRES_PASSWORD
addons_path = /mnt/extra-addons/oca,/mnt/extra-addons/ens_core,/usr/lib/python3/dist-packages/odoo/addons
without_demo = False
limit_time_real = 600
limit_time_cpu = 600
limit_time_real_cron = 600
