{  # noqa: B018
    "name": "Enswork Reports",
    "version": "17.0.1.56",
    "category": "Sales",
    "summary": "Custom report templates by Enswork",
    "author": "ENSWORK",
    "website": "https://www.enswork.com",
    "description": """
        Custom reports templates including:
        * Custom header for quotations
        * Custom header for delivery slips
        * Custom header for invoices
        * Custom header for purchase orders
    """,
    "depends": [
        "base",
        "web",
        "sale",
        "purchase",
        "stock",
        "account",
        "identifiants_fiscaux_maroc",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/security.xml",
        "data/paperformat.xml",
        "views/account_move_views.xml",
        "views/product_template_views.xml",
        "views/purchase_order_views.xml",
        "views/res_company_views.xml",
        "views/res_users_views.xml",
        "views/sale_order_views.xml",
        "views/stock_picking_views.xml",
        "data/proforma_action.xml",
        "report/report_delivery_db.xml",
        "report/report_delivery_ens.xml",
        "report/report_delivery_mec.xml",
        "report/report_receipt_db.xml",
        "report/report_receipt_ens.xml",
        "report/report_receipt_mec.xml",
        "report/report_invoice_db.xml",
        "report/report_invoice_ens.xml",
        "report/report_invoice_mec.xml",
        "report/report_proforma_db.xml",
        "report/report_proforma_disable.xml",
        "report/report_proforma_dynamic.xml",
        "report/report_proforma_ens.xml",
        "report/report_proforma_mec.xml",
        "report/report_proforma_water.xml",
        "report/report_purchase_db.xml",
        "report/report_purchase_ens.xml",
        "report/report_purchase_mec.xml",
        "report/report_rfq_db.xml",
        "report/report_rfq_ens.xml",
        "report/report_rfq_mec.xml",
        "report/report_sale_db.xml",
        "report/report_sale_db_without_ref.xml",
        "report/report_sale_ens.xml",
        "report/report_sale_ens_without_ref.xml",
        "report/report_sale_mec.xml",
        "report/report_sale_mec_without_ref.xml",
        "report/report_sale_water.xml",
        "report/report_invoice_water.xml",
        "report/report_delivery_water.xml",
        "report/report_rfq_water.xml",
        "report/report_purchase_water.xml",
        "report/report_receipt_water.xml",
        "report/report_delivery_disable.xml",
        "report/report_invoice_disable.xml",
        "report/report_purchase_disable.xml",
        "report/report_rfq_disable.xml",
        "report/report_odoo_native_disable.xml",
        "report/report_sale_disable.xml",
        "report/report_delivery_dynamic.xml",
        "report/report_invoice_dynamic.xml",
        "report/report_purchase_dynamic.xml",
        "report/report_receipt_dynamic.xml",
        "report/report_rfq_dynamic.xml",
        "report/report_sale_dynamic.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
    "license": "LGPL-3",
}
