from . import res_config_settings
from . import lines_designation
from . import force_sale_invoice_status
from . import inventory_by_category
from . import phone_unique_required
from . import add_identifiant_cnss
from . import ice_15_char
from . import account_move
from . import add_warning
from . import add_date_bon_commande
from . import block_invoice_edit
from . import sale_price_below_product_price
from . import min_discount